# Generated by Django 4.2 on 2023-05-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='about',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='word',
            name='soz_turkumi',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Soz_turkumi',
        ),
    ]
